### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by eveliotc** [fbessho/PyPoi#21]
Thanks for this awesome tool!

Just wondering if it would be possible to add a rotate option, to rotate either mask or image itself

**Comment by fbessho** [comment]
Rotate functionality has been implemented and released as [v0.2.0](https://github.com/fbessho/PyPoi/releases/tag/v0.2.0).
Please try it and let me know if you see anything (bug, comment, etc..)

If you use Mac and would like to have a binary package, please be patient for a few days. I don't have Mac available for now..

**Comment by eveliotc** [comment]
Awesome thanks a lot @fbessho
